import { Entity, Column, PrimaryGeneratedColumn, CreateDateColumn, UpdateDateColumn, Index, } from 'typeorm';
/**
 * Entity that stores each error event captured by the SDK.
 * One row = one occurrence of an error happening in a client app.
 */
@Entity({ name: 'error_events' })
@Index(['sdkKey'])
@Index(['environment'])
@Index(['createdAt'])
export class ErrorEvent {
  /**
   * Unique identifier of the error event.
   * UUID allows safe generation across distributed systems.
   */
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /**
   * Public key of the SDK that sent the error.
   * Used to identify which application/project generated the event.
   */
  @Column({ type: 'varchar', length: 255 })
  sdkKey: string;

  /**
   * Hash used to group similar errors.
   * Typically generated from message + file + line.
   * Enables aggregation, counting, and alerting.
   */
  @Column({ type: 'varchar', length: 255 })
  fingerprint: string;

  /**
   * Human-readable error message.
   * Example: "Cannot read properties of undefined"
   */
  @Column({ type: 'varchar', length: 1000 })
  message: string;

  /**
   * Full stack trace captured at runtime.
   * Stored as raw text for debugging and later parsing.
   */
  @Column({ type: 'text' })
  stackTrace: string;

  /**
   * Source file where the error occurred.
   * Example: "app.component.ts"
   */
  @Column({ type: 'varchar', length: 255 })
  file: string;

  /**
   * Line number in the source file where the error occurred.
   */
  @Column({ type: 'integer' })
  line: number;

  /**
   * Browser name where the error happened.
   * Example: Chrome, Firefox, Safari.
   */
  @Column({ type: 'varchar', length: 100 })
  browser: string;

  /**
   * Operating system of the client device.
   * Example: Windows, macOS, Linux, Android, iOS.
   */
  @Column({ type: 'varchar', length: 100 })
  os: string;

  /**
   * Environment where the error occurred.
   * Common values: production, staging, development.
   */
  @Column({ type: 'varchar', length: 50 })
  environment: string;

  /**
   * URL where the error was triggered.
   * Useful to reproduce issues in specific routes/pages.
   */
  @Column({ type: 'varchar', length: 255, nullable: true })
  url: string;

  /**
   * Application release/version running when the error occurred.
   * Helps correlate errors with deployments.
   */
  @Column({ type: 'varchar', length: 100, nullable: true })
  release: string;

  /**
   * Session identifier of the user.
   * Useful for tracing a sequence of events before the error.
   */
  @Column({ type: 'varchar', length: 255, nullable: true })
  sessionId: string;

  /**
   * Identifier of the authenticated user (if available).
   * Enables user-impact analysis.
   */
  @Column({ type: 'varchar', length: 255, nullable: true })
  userId: string;

  /**
   * Flexible JSON field for additional context.
   * Example:
   * {
   *   feature: "checkout",
   *   plan: "premium",
   *   networkStatus: "offline"
   * }
   */
  @Column({ type: 'jsonb', default: {} })
  metadata: Record<string, any>;

  /**
   * Timestamp when the error event was created (ingested).
   * Automatically generated by the database.
   */
  @CreateDateColumn()
  createdAt: Date;

  /**
   * Timestamp when the record was last updated.
   * Useful if enrichment or processing happens later.
   */
  @UpdateDateColumn()
  updatedAt: Date;
}